# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_ADMIN:         [ROLE_USER, ROLE_EDITOR]
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: AppBundle:users
                property: username
            
    encoders:
        AppBundle\Entity\users:
            algorithm: bcrypt
            cost:      13 
            
    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            provider: our_db_provider
            form_login:
                success_handler: authentication_handler
                login_path: /login
                check_path: /login_check                
            logout:    
                path: /logout
                target: /login
              
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                login_path: /login
                check_path: /login_check
                success_handler: authentication_handler
                csrf_provider: security.csrf.token_manager
                
            logout:
                path: /logout
                target: /login
                
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/admins, roles: ROLE_ADMIN }
        - { path: ^/editors, roles: ROLE_EDITOR }
        - { path: ^/users, roles: ROLE_USER }      
        - { path: ^/, roles: [ROLE_ADMIN, ROLE_USER, ROLE_EDITOR] }

